contact/urls.py
from django.urls import path
from contact import views


app_name = 'contact'

urlpatterns = [
    path('contact/<int:contact_id>/', views.contact, name='contact'),
    path('contact/create/', views.create, name='create'),
    path('search/', views.search, name='search'),
    path('', views.index, name='index'),
]

project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static 
from django.conf import settings

urlpatterns = [
    path('', include('contact.urls')),
    path('admin/', admin.site.urls),
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

contact/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User


class Category(models.Model):
    class Meta:
        verbose_name = 'Category'
        verbose_name_plural = 'Categories'
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name


class Contact(models.Model):
    first_name = models.CharField(max_length=20)
    last_name = models.CharField(max_length=20, blank=True)
    phone = models.CharField(max_length=20)
    email = models.EmailField(max_length=254, blank=True)
    created_date = models.DateTimeField(default=timezone.now)
    description = models.TextField(blank=True)
    show = models.BooleanField(default=True)
    picture = models.ImageField(blank=True, upload_to='pictures/%Y/%m/')
    category = models.ForeignKey(
        Category,
        on_delete=models.SET_NULL,
        blank=True, null=True
    )
    owner = models.ForeignKey(
        User,
        on_delete=models.SET_NULL,
        blank=True, null=True
    )

    def __str__(self):
        return f'{self.first_name} {self.last_name}'

contact/views/contact_forms.py
from django.shortcuts import render, get_object_or_404, redirect
from django.db.models import Q
from contact.models import Contact
from django.core.paginator import Paginator

def create(request):
    if request.method == 'POST':
        print()
        print(request.method)
        print(request.POST.get('first_name'))
        print(request.POST.get('last_name'))
    context = {}
    return render(request, 'contact/create.html', context)

contact/views/contact_views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.db.models import Q
from contact.models import Contact
from django.core.paginator import Paginator


def index(request):
    contacts = Contact.objects.filter(show=True).order_by('-id')
    paginator = Paginator(contacts,10)
    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)
    context = {'page_obj': page_obj, 'site_title': "Contatos -"}
    return render(request, 'contact/index.html', context)
    


def search(request):
    search_value =  request.GET.get('q','').strip()
    print(search_value)
    if search_value == '':
        return redirect('contact:index')
    contacts = Contact.objects.filter(show=True).filter(
        Q(first_name__icontains=search_value) |
        Q(last_name__icontains=search_value)
        ).order_by('-id')
    
    paginator = Paginator(contacts,10)
    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)
    
    context = {'page_obj': page_obj, 'site_title': "Search -"}
    return render(request, 'contact/index.html', context)


def contact(request, contact_id):
    single_contact = get_object_or_404(Contact, pk=contact_id, show=True)
    site_title = f'{single_contact.first_name} {single_contact.last_name} - '  
    context = {'contact': single_contact, 'site_title': site_title}
    return render(request, 'contact/contact.html', context)

contact/templates/contact/contact.html
{% extends "global/base.html" %}
{% block content %}
    <div class="single-contact">
        <h1 class="single-contact-name">
        {{contact.first_name}} {{contact.last_name}}
        </h1>
        <p><b>ID:</b> {{contact.id}}</p>
        <p><b>E-mail:</b> {{contact.email}}</p>
        <p><b>Phone:</b> {{contact.phone}}</p>
        <p><b>Created Date:</b> {{contact.created_date}}</p>
        <p><b>Description:</b> {{contact.description}}</p>
        <p><b>Category:</b> {{contact.category.name}}</p>

    </div>
{% endblock content %}

contact/templates/contact/create.html
{% extends 'global/base.html' %}

{% block content %}
  <h1>CREATE CONTACT</h1>
  <div class="form-wrapper">

    <h2>Contact</h2>

    <form 
      action="{% url 'contact:create' %}"
      method="POST"
      enctype="multipart/form-data"
    >
    {% csrf_token %}
      <div class="form-content">
        <div class="form-group">
          <label for="id_first_name">first_name</label>
          <input type="text" name="first_name" maxlength="255" id="id_first_name">
        </div>
        <div class="form-group">
          <label for="id_last_name">last_name</label>
          <input type="text" name="last_name" maxlength="255" id="id_last_name">
        </div>
      </div>

      <div class="form-content">
        <div class="form-group">
          <button class="btn" type="submit">Send</button>
        </div>
      </div>

    </form>
  </div>
{% endblock content %}

contact/templates/contact/index.html
{% extends "global/base.html" %}
{% block content %}
{% if page_obj %}
<div class="responsive-table">
    <table class="contacts-table">
        <caption class="table-caption">
            Contacts
        </caption>
        <thead>
            <tr class="table-row table-row-header">
                <th class="table-header">ID</th>
                <th class="table-header">First Name</th>
                <th class="table-header">Last Name</th>
                <th class="table-header">Phone</th>
                <th class="table-header">E-mail</th>
            </tr>
        </thead>
        <tbody>
            {% for contact in page_obj %}
                    <tr class="table-row">
                        <td class="table-cel">
                            <a class="table-link" 
                            href="{% url 'contact:contact' contact.id%}">
                            {{contact.id}}
                        </a>
                    </td>
                    <td class="table-cel">
                        {{contact.first_name}}
                    </td>
                    <td class="table-cel">
                        {{contact.last_name}}
                    </td>
                    <td class="table-cel">
                        {{contact.phone}}
                    </td>
                    <td class="table-cel">
                        {{contact.email}}
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
{% else %}
<div class="single-contact">
    <h1 class="single-contact-name">
    Nenhum contato encontrado!
    </h1>
</div>
{% endif %}
{% endblock content %}